spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none # Disable JPA if MongoDB is used
    show-sql: false
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 9080

logging:
  level:
    org.hibernate: DEBUG
    org.springframework: DEBUG
    org.springframework.data.mongodb: DEBUG
    root: DEBUG
